version: 2.1
commands:
  restore_file:
    steps:
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
  install_npm:
    steps:
      - checkout
      - run: npm i
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - install_npm
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.8
    steps:
      - checkout
      - restore_file
      - run: npm run test
  
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_file
      - run: npm audit
      - run:
          command: echo "the analyzer failed"
          when: on_fail     
          
workflows:
  ci-pipline-workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires:
            - test


        
